[project]
name = "geocoder"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "geopandas>=1.1.2",
    "pandas>=3.0.0",
    "requests>=2.32.5",
    "shapely>=2.1.2",
    "tqdm>=4.67.3",
]
